# knife
alias kcd='knife cookbook delete'
alias kcl='knife cookbook list'
alias kcu='knife cookbook upload'
alias kesl='knife ec2 server list'
alias kef='knife environment from_file'
alias kel='knife environment list'
alias kes='knife environment show'
alias kne='knife node edit'
alias knl='knife node list'
alias kns='knife node show'
alias krf='knife role from_file'
alias krl='knife role list'
alias krs='knife role show'
alias kve='knife vault edit'
alias kvs='knife vault show'
alias kvu='knife vault update'
